# coding: utf-8

"""
    Enterprise Mission Assurance Support Service (eMASS)

    The eMASS Representational State Transfer (REST) Application Programming Interface (API) enables users to perform assessments and complete actions associated with system records.  The eMASS API provides an interface for application to communicate eMASS Services. For information on how to register and use the eMASS API reference the [eMASS API Getting Started](https://mitre.github.io/emass_client/docs/eMASSGettingStarted.md).  Additional information about eMASS can be obtain by contacting the National Industrial Security Program (NISP). Points of Contact are: 

    The version of the OpenAPI document: v3.22
    Contact: disa.global.servicedesk.mbx.ma-ticket-request@mail.mil
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from emass_client.models.definition_transitions import DefinitionTransitions

class TestDefinitionTransitions(unittest.TestCase):
    """DefinitionTransitions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefinitionTransitions:
        """Test DefinitionTransitions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefinitionTransitions`
        """
        model = DefinitionTransitions()
        if include_optional:
            return DefinitionTransitions(
                end_stage = 'Submit Categorization',
                description = 'Initiate Workflow',
                roles = [
                    PM/ISO, System Admin, eMASS System Admin, ISSE, ISSM, IO
                    ]
            )
        else:
            return DefinitionTransitions(
        )
        """

    def testDefinitionTransitions(self):
        """Test DefinitionTransitions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
