# coding: utf-8

"""
    Enterprise Mission Assurance Support Service (eMASS)

    The eMASS Representational State Transfer (REST) Application Programming Interface (API) enables users to perform assessments and complete actions associated with system records.  The eMASS API provides an interface for application to communicate eMASS Services. For information on how to register and use the eMASS API reference the [eMASS API Getting Started](https://mitre.github.io/emass_client/docs/eMASSGettingStarted.md).  Additional information about eMASS can be obtain by contacting the National Industrial Security Program (NISP). Points of Contact are: 

    The version of the OpenAPI document: v3.22
    Contact: disa.global.servicedesk.mbx.ma-ticket-request@mail.mil
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from emass_client.models.milestone_response_delete import MilestoneResponseDelete

class TestMilestoneResponseDelete(unittest.TestCase):
    """MilestoneResponseDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneResponseDelete:
        """Test MilestoneResponseDelete
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneResponseDelete`
        """
        model = MilestoneResponseDelete()
        if include_optional:
            return MilestoneResponseDelete(
                meta = emass_client.models.ok.OK(
                    code = 200, ),
                data = [
                    emass_client.models.milestones_put_post_delete.MilestonesPutPostDelete(
                        system_id = 35, 
                        poam_id = 45, 
                        milestone_id = 77, 
                        external_uid = 'd6d98b88-c866-4496-9bd4-de7ba48d0f52', 
                        success = True, 
                        errors = [
                            key:value
                            ], )
                    ]
            )
        else:
            return MilestoneResponseDelete(
        )
        """

    def testMilestoneResponseDelete(self):
        """Test MilestoneResponseDelete"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
