=begin
#Enterprise Mission Assurance Support Service (eMASS)

#The eMASS Representational State Transfer (REST) Application Programming Interface (API) enables users to perform assessments and complete actions associated with system records.  The eMASS API provides an interface for application to communicate eMASS Services. For information on how to register and use the eMASS API reference the [eMASS API Getting Started](https://mitre.github.io/emass_client/docs/eMASSGettingStarted.md).  Additional information about eMASS can be obtain by contacting the National Industrial Security Program (NISP). Points of Contact are: 

The version of the OpenAPI document: v3.22
Contact: disa.global.servicedesk.mbx.ma-ticket-request@mail.mil
Generated by: https://openapi-generator.tech
Generator version: 7.12.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for EmassClient::SystemApplicationFindingsDashboardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SystemApplicationFindingsDashboardsApi' do
  before do
    # run before each test
    @api_instance = EmassClient::SystemApplicationFindingsDashboardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SystemApplicationFindingsDashboardsApi' do
    it 'should create an instance of SystemApplicationFindingsDashboardsApi' do
      expect(@api_instance).to be_instance_of(EmassClient::SystemApplicationFindingsDashboardsApi)
    end
  end

  # unit tests for get_system_application_findings_details
  # System Application Findings Details
  # Get system application findings details dashboard information.
  # @param org_id **Organization Id**: The unique organization identifier.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :excludeinherited **Exclude Inherited**: If no value is specified, the default returns false to include inherited data. 
  # @option opts [Integer] :page_index **Page Index**: If no value is specified, the default returns results from the first page with an index of 0. 
  # @option opts [Integer] :page_size **Page Size**: If no value is specified, the default returns 20000 per page. 
  # @return [GetSystemStatusDetails200Response]
  describe 'get_system_application_findings_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_system_application_findings_summary
  # System Application Findings Summary
  # Get system application findings summary dashboard information.
  # @param org_id **Organization Id**: The unique organization identifier.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :excludeinherited **Exclude Inherited**: If no value is specified, the default returns false to include inherited data. 
  # @option opts [Integer] :page_index **Page Index**: If no value is specified, the default returns results from the first page with an index of 0. 
  # @option opts [Integer] :page_size **Page Size**: If no value is specified, the default returns 20000 per page. 
  # @return [GetSystemStatusDetails200Response]
  describe 'get_system_application_findings_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
