# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from emass_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API = "/api"
    API_APIKEY = "/api/api-key"
    API_SYSTEMS = "/api/systems"
    API_SYSTEMS_SYSTEM_ID = "/api/systems/{systemId}"
    API_SYSTEMROLES = "/api/system-roles"
    API_SYSTEMROLES_ROLE_CATEGORY = "/api/system-roles/{roleCategory}"
    API_SYSTEMS_SYSTEM_ID_CONTROLS = "/api/systems/{systemId}/controls"
    API_SYSTEMS_SYSTEM_ID_TESTRESULTS = "/api/systems/{systemId}/test-results"
    API_SYSTEMS_SYSTEM_ID_POAMS = "/api/systems/{systemId}/poams"
    API_SYSTEMS_SYSTEM_ID_POAMS_POAM_ID = "/api/systems/{systemId}/poams/{poamId}"
    API_SYSTEMS_SYSTEM_ID_POAMS_POAM_ID_MILESTONES = "/api/systems/{systemId}/poams/{poamId}/milestones"
    API_SYSTEMS_SYSTEM_ID_POAMS_POAM_ID_MILESTONES_MILESTONE_ID = "/api/systems/{systemId}/poams/{poamId}/milestones/{milestoneId}"
    API_SYSTEMS_SYSTEM_ID_ARTIFACTS = "/api/systems/{systemId}/artifacts"
    API_SYSTEMS_SYSTEM_ID_ARTIFACTSEXPORT = "/api/systems/{systemId}/artifacts-export"
    API_SYSTEMS_SYSTEM_ID_APPROVAL_CAC = "/api/systems/{systemId}/approval/cac"
    API_SYSTEMS_SYSTEM_ID_APPROVAL_PAC = "/api/systems/{systemId}/approval/pac"
    API_CMMCASSESSMENTS = "/api/cmmc-assessments"
    API_SYSTEMS_SYSTEM_ID_STATICCODESCANS = "/api/systems/{systemId}/static-code-scans"
    API_WORKFLOWS_DEFINITIONS = "/api/workflows/definitions"
    API_WORKFLOWS_INSTANCES = "/api/workflows/instances"
    API_WORKFLOWS_INSTANCES_WORKFLOW_INSTANCE_ID = "/api/workflows/instances/{workflowInstanceId}"
    API_SYSTEMS_SYSTEM_ID_CLOUDRESOURCERESULTS = "/api/systems/{systemId}/cloud-resource-results"
    API_SYSTEMS_SYSTEM_ID_CONTAINERSCANRESULTS = "/api/systems/{systemId}/container-scan-results"
    API_DASHBOARDS_SYSTEMSTATUSDETAILS = "/api/dashboards/system-status-details"
    API_DASHBOARDS_SYSTEMCONTROLCOMPLIANCESUMMARY = "/api/dashboards/system-control-compliance-summary"
    API_DASHBOARDS_SYSTEMSECURITYCONTROLSDETAILS = "/api/dashboards/system-security-controls-details"
    API_DASHBOARDS_SYSTEMASSESSMENTPROCEDURESDETAILS = "/api/dashboards/system-assessment-procedures-details"
    API_DASHBOARDS_SYSTEMPOAMSUMMARY = "/api/dashboards/system-poam-summary"
    API_DASHBOARDS_SYSTEMPOAMDETAILS = "/api/dashboards/system-poam-details"
    API_DASHBOARDS_SYSTEMARTIFACTSSUMMARY = "/api/dashboards/system-artifacts-summary"
    API_DASHBOARDS_SYSTEMARTIFACTSDETAILS = "/api/dashboards/system-artifacts-details"
    API_DASHBOARDS_SYSTEMHARDWARESUMMARY = "/api/dashboards/system-hardware-summary"
    API_DASHBOARDS_SYSTEMHARDWAREDETAILS = "/api/dashboards/system-hardware-details"
    API_DASHBOARDS_SYSTEMSENSORHARDWARESUMMARY = "/api/dashboards/system-sensor-hardware-summary"
    API_DASHBOARDS_SYSTEMSENSORHARDWAREDETAILS = "/api/dashboards/system-sensor-hardware-details"
    API_DASHBOARDS_SYSTEMPORTSPROTOCOLSSUMMARY = "/api/dashboards/system-ports-protocols-summary"
    API_DASHBOARDS_SYSTEMPORTSPROTOCOLSDETAILS = "/api/dashboards/system-ports-protocols-details"
    API_DASHBOARDS_SYSTEMASSOCIATIONSDETAILS = "/api/dashboards/system-associations-details"
    API_DASHBOARDS_USERSYSTEMASSIGNMENTSDETAILS = "/api/dashboards/user-system-assignments-details"
    API_DASHBOARDS_SYSTEMPRIVACYSUMMARY = "/api/dashboards/system-privacy-summary"
    API_DASHBOARDS_VAOMBFISMASAOPSUMMARY = "/api/dashboards/va-omb-fisma-saop-summary"
    API_DASHBOARDS_VASYSTEMAASUMMARY = "/api/dashboards/va-system-aa-summary"
    API_DASHBOARDS_VASYSTEMA2SUMMARY = "/api/dashboards/va-system-a2-summary"
    API_DASHBOARDS_VASYSTEMPL109REPORTINGSUMMARY = "/api/dashboards/va-system-pl-109-reporting-summary"
    API_DASHBOARDS_VASYSTEMFISMAINVENTORYSUMMARY = "/api/dashboards/va-system-fisma-inventory-summary"
    API_DASHBOARDS_VASYSTEMFISMAINVENTORYCRYPTOSUMMARY = "/api/dashboards/va-system-fisma-inventory-crypto-summary"
    API_DASHBOARDS_VASYSTEMTHREATRISKSSUMMARY = "/api/dashboards/va-system-threat-risks-summary"
    API_DASHBOARDS_VASYSTEMTHREATSOURCESDETAILS = "/api/dashboards/va-system-threat-sources-details"
    API_DASHBOARDS_VASYSTEMTHREATARCHITECTUREDETAILS = "/api/dashboards/va-system-threat-architecture-details"
