name: Build and Release to NPM
on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Build the NPM Package
        run: |
          cd src/typescript_client
          npm install
          npm run build

      - name: Pack all items that are published as packages
        run: |
          cd src/typescript_client
          npm pack
     
      # Publish to npm Registry
      - name: Publish emass_client to NPM
        if: always()
        run: |
          cd src/typescript_client
          npm publish --access public mitre-emass_client-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        if: always()
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish emass_client to GitHub Packages
        if: always()
        run: npm publish --access public mitre-emass_client-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}