name: Build and Release to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write # required for trusted publishing's use of OIDC
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          registry-url: 'https://registry.npmjs.org'

      - name: Manually update npm to 11.5.1 or later which is the required version for trusted publishing to work # this step can be removed after the ubuntu runner has the correct minimum version of npm installed
        run: npm install -g npm@latest

      - name: Build the NPM Package
        run: |
          cd src/typescript_client
          npm install
          npm run build

      - name: Pack all items that are published as packages
        run: |
          cd src/typescript_client
          npm pack
     
      # Publish to npm Registry
      - name: Publish emass_client to NPM
        if: always()
        run: |
          cd src/typescript_client
          npm publish --access public mitre-emass_client-*.tgz
